services:

  backend:
    build:
      context: ./backend

    container_name: geografica-api

    ports:
      - "8000:8000"

    env_file:
      - ./backend/.env

    restart: unless-stopped

  frontend:
    build:
      context: ./frontend

    container_name: geografica-frontend

    ports:
      - "3000:3000"

    restart: unless-stopped

    depends_on:
      - backend

  mariadb:
    image: mariadb:11

    container_name: geografica-db

    environment:
      MYSQL_ROOT_PASSWORD: geografica123
      MYSQL_DATABASE: geografica

    volumes:
      - geografica_db_data:/var/lib/mysql

    restart: unless-stopped

volumes: 
  geografica_db_data:
